name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/blogs_mkdocs
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build MkDocs site
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} mkdocs build --verbose --site-dir site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Deploy only from the main branch
        run: |
          docker run --rm -v ${{ github.workspace }}/site:/site ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ghp-import -n -p -f /site

      - name: Clean up Docker resources
        run: docker system prune -f  # Clean up any dangling Docker resources to save space
