name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/blogs_mkdocs
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetche to avoid issues with ghp-impo

      - name: Build MkDocs site
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} mkdocs build --verbose --site-dir site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} /bin/bash -c "
            git config --global --add safe.directory /app &&
            ghp-import -n -p -f site"
      - name: Clean up Docker resources
        run: docker system prune -f
